services:
  backend:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - .env
      - .env.prod
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - '3306:3306'
    env_file:
      - .env
      - .env.prod
    volumes:
      - sigizi:/var/lib/mysql

volumes:
  sigizi:
