services:
  backend:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - .env
      - .env.prod
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - '3306:3306'
    env_file:
      - .env
      - .env.prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - sigizi:/var/lib/mysql

volumes:
  sigizi:
